---
- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariaDB-server
      yum:
        name: mariadb-server
        state: present

    - name: Start MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes


    - name: Install PyMySQL dependency
      ansible.builtin.yum:
        name: python3-PyMySQL # Or other specific package name
        state: present


    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: bobdata
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      become: yes

    - name: Create database user with name 'bob' and password '12345' with all database privileges
      mysql_user:
        name: bob
        password: 12345
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      become: yes

