- name: Install and configure time sync service based on OS
  hosts: all
  become: true

  tasks:
    - name: Install chrony on CentOS
      ansible.builtin.yum:
        name: chrony
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install ntp on Ubuntu
      ansible.builtin.apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Start and enable chrony service on CentOS
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Start and enable ntp service on Ubuntu
      ansible.builtin.service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"

